### PR TITLE
add Authenticate middleware

### PR DESCRIPTION
**Pull request by odupont**
Add an Authenticate middleware to override the original one from Illuminate.

If you pass many guards to auth middleware, you don't need the guard as parameter on $request->user() method anymore.

Avoid issue that return user with same id on another provider.

### CODE REVIEW

**Comment by sfelix-martins** [comment]
@odupont Thanks for your pull request. I'm testing and I'll give you an answer as soon as I'm done.

**Comment by sfelix-martins** [comment]
@odupont In all tests I received a `Unauthenticated` exception.

It's my `configs/auth.php` file:

```php
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'customers',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'customers',
        ],

        'admin' => [
            'driver' => 'passport',
            'provider' => 'admins',
        ],
    ],

    'providers' => [
        'customers' => [
            'driver' => 'eloquent',
            'model' => App\Customer::class,
        ],

        'admins' => [
            'driver' => 'eloquent',
            'model' => App\Admin::class,
        ],
    ],
```

And my routes:

```php
Route::middleware('auth:api')->get('/customer', function (Request $request) {
    return $request->user();
});

Route::middleware('auth:admin')->get('/admin', function (Request $request) {
    return $request->user();
});

Route::middleware('auth:api,admin')->get('/users', function (Request $request) {
    $user = $request->user();
    if ($user instanceof \App\User) {
        return 'user';
    } elseif ($user instanceof \App\Customer) {
        return 'customer';
    }

    return $user;
});

```

**Comment by odupont** [comment]
@sfelix-martins Oh, there was a mistake in my code between guards and providers, in my _configs/auth.php_ they were the same.
Should be fixed now.

**Comment by sfelix-martins** [comment]
@odupont I'm sorry. I got carried away and I ended up doing of its pull request a preparation for a new release. Ops.

**Comment by odupont** [comment]
@sfelix-martins no problem, I'm glad this contribution is useful.

**Comment by sfelix-martins** [comment]
@odupont Can you help me on tests? I added the unit and feature tests to your middleware and trait to help on unit tests (`SMartins\PassportMultiauth\Testing\MultiauthActions`). The instructions to use are on README. 

Thanks!

**Pull request merged**
